ws_server_homepage:
    path:     /
    defaults: { _controller: WSServerBundle:Default:index }

ws_server_logging:
    path:     /logging
    defaults: { _controller: WSServerBundle:Auth:index }

ws_server_postcash:
    path:     /postcash
    defaults: { _controller: WSServerBundle:PostCash:postcash }
ws_server_postcash_test_client:
    path:     /postcashtestclient
    defaults: { _controller: WSServerBundle:PostCash:postcashtestclient }

ws_server_expressocash:
    path:     /expressocash
    defaults: { _controller: WSServerBundle:ExpressoCash:expressocash }

ws_server_tnt:
    path:     /tnt
    defaults: { _controller: WSServerBundle:Tnt:tnt }

ws_server_ecommerce:
    path:     /ecommerce
    defaults: { _controller: WSServerBundle:Ecommerce:ecommerce }


