ws_server_homepage:
    path:     /
    defaults: { _controller: WSServerBundle:Default:index }

ws_server_logging:
    path:     /logging
    defaults: { _controller: WSServerBundle:Auth:index }

ws_server_postcash:
    path:     /postcash
    defaults: { _controller: WSServerBundle:PostCash:postcash }
