############################################
############################################
#     Local Service

ws_server_homepage:
    path:     /
    defaults: { _controller: WSServerBundle:Default:index }

ws_server_logging:
    path:     /logging
    defaults: { _controller: WSServerBundle:Auth:index }

ws_server_ecommerce:
    path:     /ecommerce
    defaults: { _controller: WSServerBundle:Ecommerce:ecommerce }

ws_server_adminpdv:
    path:     /adminpdv
    defaults: { _controller: WSServerBundle:Adminpdv:adminpdv }

ws_server_adminmultipdv:
    path:     /adminmultipdv
    defaults: { _controller: WSServerBundle:Adminmultipdv:adminmultipdv }

ws_server_maps:
    path:     /maps
    defaults: { _controller: WSServerBundle:Maps:maps }

ws_server_comptapdv:
    path:     /comptapdv
    defaults: { _controller: WSServerBundle:Comptapdv:comptapdv }



#########################################################
#########################################################
#     API Service Partenaire

ws_server_postcash:
    path:     /postcash
    defaults: { _controller: WSServerBundle:PostCash:postcash }

ws_server_expressocash:
    path:     /expressocash
    defaults: { _controller: WSServerBundle:ExpressoCash:expressocash }

ws_server_jonijoni:
    path:     /jonijoni
    defaults: { _controller: WSServerBundle:JoniJoni:jonijoni }

ws_server_tnt:
    path:     /tnt
    defaults: { _controller: WSServerBundle:Tnt:tnt }
