ws_client_homepage:
    path:     /
    defaults: { _controller: WSClientBundle:Default:index }



ws_client_logging:
    path:     /logging
    defaults: { _controller: WSClientBundle:Default:logging }
ws_client_disconnexion:
    path:     /deconnexion
    defaults: { _controller: WSClientBundle:Default:disconnect }



ws_client_postcash_getcardusername:
    path:     /postcash/getcardusername
    defaults: { _controller: WSClientBundle:PostCash:getcardusername }
ws_client_postcash_getfraispartenaire:
    path:     /postcash/getfraispartenaire
    defaults: { _controller: WSClientBundle:PostCash:getfraispartenaire }
ws_client_postcash_rechargementespece:
    path:     /postcash/rechargementespece
    defaults: { _controller: WSClientBundle:PostCash:rechargementespece }
ws_client_postcash_retraitespece:
    path:     /postcash/retraitespece
    defaults: { _controller: WSClientBundle:PostCash:retraitespece }
ws_client_postcash_debitercarte:
    path:     /postcash/debitercarte
    defaults: { _controller: WSClientBundle:PostCash:debitercarte }
ws_client_postcash_debitcartedirect:
    path:     /postcash/debitcartedirect
    defaults: { _controller: WSClientBundle:PostCash:debitcartedirect }
ws_client_postcash_codevalidation:
    path:     /postcash/codevalidation
    defaults: { _controller: WSClientBundle:PostCash:codevalidation }
ws_client_postcash_achatcodewoyofal:
    path:     /postcash/achatcodewoyofal
    defaults: { _controller: WSClientBundle:PostCash:achatcodewoyofal }
ws_client_postcash_reglementsenelec:
    path:     /postcash/reglementsenelec
    defaults: { _controller: WSClientBundle:PostCash:reglementsenelec }
ws_client_postcash_detailfacturesenelec:
    path:     /postcash/detailfacturesenelec
    defaults: { _controller: WSClientBundle:PostCash:detailfacturesenelec }
ws_client_postcash_achatneo:
    path:     /postcash/achatneo
    defaults: { _controller: WSClientBundle:PostCash:achatneo }
ws_client_postcash_achatjula:
    path:     /postcash/achatjula
    defaults: { _controller: WSClientBundle:PostCash:achatjula }
ws_client_postcash_getinfosnumber:
    path:     /postcash/getinfosnumber
    defaults: { _controller: WSClientBundle:PostCash:getinfosnumber }
ws_client_postcash_getinfosnumberap:
    path:     /postcash/getinfosnumberap
    defaults: { _controller: WSClientBundle:PostCash:getinfosnumberap }
ws_client_postcash_achatcredittelephonique:
    path:     /postcash/achatcredittelephonique
    defaults: { _controller: WSClientBundle:PostCash:achatcredittelephonique }
ws_client_postcash_cashtocashsend:
    path:     /postcash/cashtocashsend
    defaults: { _controller: WSClientBundle:PostCash:cashtocashsend }
ws_client_postcash_cashtocashreceive:
    path:     /postcash/cashtocashreceive
    defaults: { _controller: WSClientBundle:PostCash:cashtocashreceive }
ws_client_postcash_transfertverstamtam:
    path:     /postcash/transfertverstamtam
    defaults: { _controller: WSClientBundle:PostCash:transfertverstamtam }
ws_client_postcash_consultersoldeneo:
    path:     /postcash/consultersoldeneo
    defaults: { _controller: WSClientBundle:PostCash:consultersoldeneo }
ws_client_postcash_debitercompteneo:
    path:     /postcash/debitercompteneo
    defaults: { _controller: WSClientBundle:PostCash:debitercompteneo }
ws_client_postcash_saveachatneo:
    path:     /postcash/saveachatneo
    defaults: { _controller: WSClientBundle:PostCash:saveachatneo }
ws_client_postcash_transfertverstamtamviaapay:
    path:     /postcash/transfertverstamtamviaapay
    defaults: { _controller: WSClientBundle:PostCash:transfertverstamtamviaapay }
ws_client_postcash_fraistamtamviaapay:
    path:     /postcash/fraistamtamviaapay
    defaults: { _controller: WSClientBundle:PostCash:fraistamtamviaapay }
ws_client_postcash_histotransactmarchand:
    path:     /postcash/histotransactmarchand
    defaults: { _controller: WSClientBundle:PostCash:histotransactmarchand }



ws_client_expressocash_checkbalance:
    path:     /expressocash/checkbalance
    defaults: { _controller: WSClientBundle:ExpressoCash:checkbalance }



ws_client_tnt_verifinumeroabonnement:
    path:     /tnt/verifinumeroabonnement
    defaults: { _controller: WSClientBundle:Tnt:verifinumeroabonnement }
ws_client_tnt_listabonnement:
    path:     /tnt/listabonnement
    defaults: { _controller: WSClientBundle:Tnt:listabonnement }
ws_client_tnt_ajoutabonnement:
    path:     /tnt/ajoutabonnement
    defaults: { _controller: WSClientBundle:Tnt:ajoutabonnement }
ws_client_tnt_ventedecodeur:
    path:     /tnt/ventedecodeur
    defaults: { _controller: WSClientBundle:Tnt:ventedecodeur }

ws_client_tnt_ventecarte:
    path:     /tnt/ventecarte
    defaults: { _controller: WSClientBundle:Tnt:ventecarte }

ws_client_tnt_listdecodeur:
    path:     /tnt/listdecodeur
    defaults: { _controller: WSClientBundle:Tnt:listdecodeur }

ws_client_tnt_listcarte:
    path:     /tnt/listcarte
    defaults: { _controller: WSClientBundle:Tnt:listcarte }


ws_client_ecommerce_ajoutarticle:
    path:     /ecommerce/ajoutarticle
    defaults: { _controller: WSClientBundle:Ecommerce:ajoutarticle }
ws_client_ecommerce_ajoutcommande:
    path:     /ecommerce/ajoutcommande
    defaults: { _controller: WSClientBundle:Ecommerce:ajoutcommande }
ws_client_ecommerce_ajoutvente:
    path:     /ecommerce/ajoutvente
    defaults: { _controller: WSClientBundle:Ecommerce:ajoutvente }
ws_client_ecommerce_listerarticle:
    path:     /ecommerce/listerarticle
    defaults: { _controller: WSClientBundle:Ecommerce:listerarticle }
ws_client_ecommerce_listercommande:
    path:     /ecommerce/listercommande
    defaults: { _controller: WSClientBundle:Ecommerce:listercommande }
ws_client_ecommerce_listervente:
    path:     /ecommerce/listervente
    defaults: { _controller: WSClientBundle:Ecommerce:listervente }



ws_client_adminpdv_montanttransfertservice:
    path:     /adminpdv/montanttransfertservice
    defaults: { _controller: WSClientBundle:Adminpdv:montanttransfertservice }
ws_client_adminpdv_performancepdv:
    path:     /adminpdv/performancepdv
    defaults: { _controller: WSClientBundle:Adminpdv:performancepdv }
ws_client_adminpdv_notifications:
    path:     /adminpdv/notifications
    defaults: { _controller: WSClientBundle:Adminpdv:notifications }
ws_client_adminpdv_bilandeposit:
    path:     /adminpdv/bilandeposit
    defaults: { _controller: WSClientBundle:Adminpdv:bilandeposit }
ws_client_adminpdv_consommationdepositservice:
    path:     /adminpdv/consommationdepositservice
    defaults: { _controller: WSClientBundle:Adminpdv:consommationdepositservice }
ws_client_adminpdv_consommationdepositpdv:
    path:     /adminpdv/consommationdepositpdv
    defaults: { _controller: WSClientBundle:Adminpdv:consommationdepositpdv }
ws_client_adminpdv_historiquerecouvrement:
    path:     /adminpdv/historiquerecouvrement
    defaults: { _controller: WSClientBundle:Adminpdv:historiquerecouvrement }
ws_client_adminpdv_historiquereclamation:
    path:     /adminpdv/historiquereclamation
    defaults: { _controller: WSClientBundle:Adminpdv:historiquereclamation }
