ws_client_homepage:
    path:     /
    defaults: { _controller: WSClientBundle:Default:index }

ws_client_logging:
    path:     /logging
    defaults: { _controller: WSClientBundle:Default:logging }

ws_client_disconnexion:
    path:     /deconnexion
    defaults: { _controller: WSClientBundle:Default:disconnect }


ws_client_postcash_rechargementespece:
    path:     /postcash/rechargementespece
    defaults: { _controller: WSClientBundle:PostCash:rechargementespece }

ws_client_postcash_retraitespece:
    path:     /postcash/retraitespece
    defaults: { _controller: WSClientBundle:PostCash:retraitespece }

ws_client_postcash_achatcodewoyofal:
    path:     /postcash/achatcodewoyofal
    defaults: { _controller: WSClientBundle:PostCash:achatcodewoyofal }

ws_client_postcash_reglementsenelec:
    path:     /postcash/reglementsenelec
    defaults: { _controller: WSClientBundle:PostCash:reglementsenelec }

ws_client_postcash_achatjula:
    path:     /postcash/achatjula
    defaults: { _controller: WSClientBundle:PostCash:achatjula }

ws_client_postcash_achatcredittelephonique:
    path:     /postcash/achatcredittelephonique
    defaults: { _controller: WSClientBundle:PostCash:achatcredittelephonique }


ws_client_expressocash_checkbalance:
    path:     /expressocash/checkbalance
    defaults: { _controller: WSClientBundle:ExpressoCash:checkbalance }


ws_client_tnt_verifinumeroabonnement:
    path:     /tnt/verifinumeroabonnement
    defaults: { _controller: WSClientBundle:Tnt:verifinumeroabonnement }

ws_client_tnt_listabonnement:
    path:     /tnt/listabonnement
    defaults: { _controller: WSClientBundle:Tnt:listabonnement }

ws_client_tnt_ajoutabonnement:
    path:     /tnt/ajoutabonnement
    defaults: { _controller: WSClientBundle:Tnt:ajoutabonnement }

ws_client_tnt_ventedecodeur:
    path:     /tnt/ventedecodeur
    defaults: { _controller: WSClientBundle:Tnt:ventedecodeur }

ws_client_tnt_listdecodeur:
    path:     /tnt/listdecodeur
    defaults: { _controller: WSClientBundle:Tnt:listdecodeur }


ws_client_ecommerce_ajoutarticle:
    path:     /ecommerce/ajoutarticle
    defaults: { _controller: WSClientBundle:Ecommerce:ajoutarticle }

ws_client_ecommerce_ajoutcommande:
    path:     /ecommerce/ajoutcommande
    defaults: { _controller: WSClientBundle:Ecommerce:ajoutcommande }

ws_client_ecommerce_ajoutvente:
    path:     /ecommerce/ajoutvente
    defaults: { _controller: WSClientBundle:Ecommerce:ajoutvente }

ws_client_ecommerce_listerarticle:
    path:     /ecommerce/listerarticle
    defaults: { _controller: WSClientBundle:Ecommerce:listerarticle }

ws_client_ecommerce_listercommande:
    path:     /ecommerce/listercommande
    defaults: { _controller: WSClientBundle:Ecommerce:listercommande }

ws_client_ecommerce_listervente:
    path:     /ecommerce/listervente
    defaults: { _controller: WSClientBundle:Ecommerce:listervente }


ws_client_adminpdv_montanttransfertservice:
    path:     /adminpdv/montanttransfertservice
    defaults: { _controller: WSClientBundle:Adminpdv:montanttransfertservice }