ws_client_homepage:
    path:     /
    defaults: { _controller: WSClientBundle:Default:index }



ws_client_logging:
    path:     /logging
    defaults: { _controller: WSClientBundle:Default:logging }
ws_client_disconnexion:
    path:     /deconnexion
    defaults: { _controller: WSClientBundle:Default:disconnect }

sms_ing:
    path:     /send_sms
    defaults: { _controller: WSClientBundle:Default:sms }

ws_client_commercial:
    path:     /commercial/listcoursier
    defaults: { _controller: WSClientBundle:Commercial:listcoursier }


ws_client_postcash_getcardusername:
    path:     /postcash/getcardusername
    defaults: { _controller: WSClientBundle:PostCash:getcardusername }
ws_client_postcash_getfraispartenaire:
    path:     /postcash/getfraispartenaire
    defaults: { _controller: WSClientBundle:PostCash:getfraispartenaire }
ws_client_postcash_rechargementespece:
    path:     /postcash/rechargementespece
    defaults: { _controller: WSClientBundle:PostCash:rechargementespece }
ws_client_postcash_retraitespece:
    path:     /postcash/retraitespece
    defaults: { _controller: WSClientBundle:PostCash:retraitespece }
ws_client_postcash_debitercarte:
    path:     /postcash/debitercarte
    defaults: { _controller: WSClientBundle:PostCash:debitercarte }
ws_client_postcash_debitcartedirect:
    path:     /postcash/debitcartedirect
    defaults: { _controller: WSClientBundle:PostCash:debitcartedirect }
ws_client_postcash_codevalidation:
    path:     /postcash/codevalidation
    defaults: { _controller: WSClientBundle:PostCash:codevalidation }
ws_client_postcash_achatcodewoyofal:
    path:     /postcash/achatcodewoyofal
    defaults: { _controller: WSClientBundle:PostCash:achatcodewoyofal }
ws_client_postcash_reglementsenelec:
    path:     /postcash/reglementsenelec
    defaults: { _controller: WSClientBundle:PostCash:reglementsenelec }
ws_client_postcash_detailfacturesenelec:
    path:     /postcash/detailfacturesenelec
    defaults: { _controller: WSClientBundle:PostCash:detailfacturesenelec }
ws_client_postcash_achatneo:
    path:     /postcash/achatneo
    defaults: { _controller: WSClientBundle:PostCash:achatneo }
ws_client_postcash_achatjula:
    path:     /postcash/achatjula
    defaults: { _controller: WSClientBundle:PostCash:achatjula }
ws_client_postcash_getinfosnumber:
    path:     /postcash/getinfosnumber
    defaults: { _controller: WSClientBundle:PostCash:getinfosnumber }
ws_client_postcash_getinfosnumberap:
    path:     /postcash/getinfosnumberap
    defaults: { _controller: WSClientBundle:PostCash:getinfosnumberap }
ws_client_postcash_achatcredittelephonique:
    path:     /postcash/achatcredittelephonique
    defaults: { _controller: WSClientBundle:PostCash:achatcredittelephonique }
ws_client_postcash_cashtocashsend:
    path:     /postcash/cashtocashsend
    defaults: { _controller: WSClientBundle:PostCash:cashtocashsend }
ws_client_postcash_cashtocashreceive:
    path:     /postcash/cashtocashreceive
    defaults: { _controller: WSClientBundle:PostCash:cashtocashreceive }
ws_client_postcash_transfertverstamtam:
    path:     /postcash/transfertverstamtam
    defaults: { _controller: WSClientBundle:PostCash:transfertverstamtam }
ws_client_postcash_consultersoldeneo:
    path:     /postcash/consultersoldeneo
    defaults: { _controller: WSClientBundle:PostCash:consultersoldeneo }
ws_client_postcash_debitercompteneo:
    path:     /postcash/debitercompteneo
    defaults: { _controller: WSClientBundle:PostCash:debitercompteneo }
ws_client_postcash_saveachatneo:
    path:     /postcash/saveachatneo
    defaults: { _controller: WSClientBundle:PostCash:saveachatneo }
ws_client_postcash_transfertverstamtamviaapay:
    path:     /postcash/transfertverstamtamviaapay
    defaults: { _controller: WSClientBundle:PostCash:transfertverstamtamviaapay }
ws_client_postcash_fraistamtamviaapay:
    path:     /postcash/fraistamtamviaapay
    defaults: { _controller: WSClientBundle:PostCash:fraistamtamviaapay }
ws_client_postcash_histotransactmarchand:
    path:     /postcash/histotransactmarchand
    defaults: { _controller: WSClientBundle:PostCash:histotransactmarchand }



ws_client_expressocash_cashin:
    path:     /expressocash/cashin
    defaults: { _controller: WSClientBundle:ExpressoCash:cashin }
ws_client_expressocash_cashout:
    path:     /expressocash/cashout
    defaults: { _controller: WSClientBundle:ExpressoCash:cashout }
ws_client_expressocash_topup:
    path:     /expressocash/topup
    defaults: { _controller: WSClientBundle:ExpressoCash:topup }
ws_client_expressocash_checkbalance:
    path:     /expressocash/checkbalance
    defaults: { _controller: WSClientBundle:ExpressoCash:checkbalance }



ws_client_jonijoni_cashtocash_getcommissionsttc:
    path:     /jonijoni/cashtocash_getcommissionsttc
    defaults: { _controller: WSClientBundle:JoniJoni:cashtocash_getcommissionsttc }
ws_client_jonijoni_cashtocash_sendtransaction:
    path:     /jonijoni/cashtocash_sendtransaction
    defaults: { _controller: WSClientBundle:JoniJoni:cashtocash_sendtransaction }
ws_client_jonijoni_cashtocash_checktransactioncode:
    path:     /jonijoni/cashtocash_checktransactioncode
    defaults: { _controller: WSClientBundle:JoniJoni:cashtocash_checktransactioncode }
ws_client_jonijoni_cashtocash_paytransaction:
    path:     /jonijoni/cashtocash_paytransaction
    defaults: { _controller: WSClientBundle:JoniJoni:cashtocash_paytransaction }
ws_client_jonijoni_cashtocash_canceltransaction:
    path:     /jonijoni/cashtocash_canceltransaction
    defaults: { _controller: WSClientBundle:JoniJoni:cashtocash_canceltransaction }
ws_client_jonijoni_vitfe_getinfocomptevitfe:
    path:     /jonijoni/vitfe_getinfocomptevitfe
    defaults: { _controller: WSClientBundle:JoniJoni:vitfe_getinfocomptevitfe }
ws_client_jonijoni_vitfe_getcommissionsttcvitfe:
    path:     /jonijoni/vitfe_getcommissionsttcvitfe
    defaults: { _controller: WSClientBundle:JoniJoni:vitfe_getcommissionsttcvitfe }
ws_client_jonijoni_vitfe_approcompte:
    path:     /jonijoni/vitfe_approcompte
    defaults: { _controller: WSClientBundle:JoniJoni:vitfe_approcompte }
ws_client_jonijoni_monetique_getinfocarte:
    path:     /jonijoni/monetique_getinfocarte
    defaults: { _controller: WSClientBundle:JoniJoni:monetique_getinfocarte }
ws_client_jonijoni_monetique_getcommissionsttccarte:
    path:     /jonijoni/monetique_getcommissionsttccarte
    defaults: { _controller: WSClientBundle:JoniJoni:monetique_getcommissionsttccarte }
ws_client_jonijoni_monetique_rechargecarte:
    path:     /jonijoni/monetique_rechargecarte
    defaults: { _controller: WSClientBundle:JoniJoni:monetique_rechargecarte }



ws_client_tnt_verifinumeroabonnement:
    path:     /tnt/verifinumeroabonnement
    defaults: { _controller: WSClientBundle:Tnt:verifinumeroabonnement }
ws_client_tnt_listabonnement:
    path:     /tnt/listabonnement
    defaults: { _controller: WSClientBundle:Tnt:listabonnement }
ws_client_tnt_ajoutabonnement:
    path:     /tnt/ajoutabonnement
    defaults: { _controller: WSClientBundle:Tnt:ajoutabonnement }
ws_client_tnt_ventedecodeur:
    path:     /tnt/ventedecodeur
    defaults: { _controller: WSClientBundle:Tnt:ventedecodeur }
ws_client_tnt_ventecarte:
    path:     /tnt/ventecarte
    defaults: { _controller: WSClientBundle:Tnt:ventecarte }
ws_client_tnt_listdecodeur:
    path:     /tnt/listdecodeur
    defaults: { _controller: WSClientBundle:Tnt:listdecodeur }
ws_client_tnt_listcarte:
    path:     /tnt/listcarte
    defaults: { _controller: WSClientBundle:Tnt:listcarte }



ws_client_outsitecommerce_listerarticleecomoutsite:
    path:     /outsitecommerce/listerarticleecomoutsite
    defaults: { _controller: WSClientBundle:OutsitEcommerce:listerarticleecomoutsite }
ws_client_outsitecommerce_listerzoneecomoutsite:
    path:     /outsitecommerce/listerzoneecomoutsite
    defaults: { _controller: WSClientBundle:OutsitEcommerce:listerzoneecomoutsite }
ws_client_outsitecommerce_listercategorieecomoutsite:
    path:     /outsitecommerce/listercategorieecomoutsite
    defaults: { _controller: WSClientBundle:OutsitEcommerce:listercategorieecomoutsite }



ws_client_ecommerce_ajoutarticle:
    path:     /ecommerce/ajoutarticle
    defaults: { _controller: WSClientBundle:Ecommerce:ajoutarticle }
ws_client_ecommerce_ajoutcommande:
    path:     /ecommerce/ajoutcommande
    defaults: { _controller: WSClientBundle:Ecommerce:ajoutcommande }
ws_client_ecommerce_ajoutvente:
    path:     /ecommerce/ajoutvente
    defaults: { _controller: WSClientBundle:Ecommerce:ajoutvente }
ws_client_ecommerce_listerarticle:
    path:     /ecommerce/listerarticle
    defaults: { _controller: WSClientBundle:Ecommerce:listerarticle }
ws_client_ecommerce_listercommande:
    path:     /ecommerce/listercommande
    defaults: { _controller: WSClientBundle:Ecommerce:listercommande }
ws_client_ecommerce_listervente:
    path:     /ecommerce/listervente
    defaults: { _controller: WSClientBundle:Ecommerce:listervente }



ws_client_adminpdv_listuserpdv:
    path:     /adminpdv/listuserpdv
    defaults: { _controller: WSClientBundle:Adminpdv:listuserpdv }
ws_client_adminpdv_montanttransfertservice:
    path:     /adminpdv/montanttransfertservice
    defaults: { _controller: WSClientBundle:Adminpdv:montanttransfertservice }
ws_client_adminpdv_performancepdv:
    path:     /adminpdv/performancepdv
    defaults: { _controller: WSClientBundle:Adminpdv:performancepdv }
ws_client_adminpdv_notifications:
    path:     /adminpdv/notifications
    defaults: { _controller: WSClientBundle:Adminpdv:notifications }
ws_client_adminpdv_bilandeposit:
    path:     /adminpdv/bilandeposit
    defaults: { _controller: WSClientBundle:Adminpdv:bilandeposit }
ws_client_adminpdv_consommationdepositservice:
    path:     /adminpdv/consommationdepositservice
    defaults: { _controller: WSClientBundle:Adminpdv:consommationdepositservice }
ws_client_adminpdv_consommationdepositpdv:
    path:     /adminpdv/consommationdepositpdv
    defaults: { _controller: WSClientBundle:Adminpdv:consommationdepositpdv }
ws_client_adminpdv_historiquerecouvrement:
    path:     /adminpdv/historiquerecouvrement
    defaults: { _controller: WSClientBundle:Adminpdv:historiquerecouvrement }
ws_client_adminpdv_historiquereclamation:
    path:     /adminpdv/historiquereclamation
    defaults: { _controller: WSClientBundle:Adminpdv:historiquereclamation }
ws_client_adminpdv_nombredereclamationpdvvente:
    path:     /adminpdv/nombredereclamationpdvvente
    defaults: { _controller: WSClientBundle:Adminpdv:nombredereclamationpdvvente }



ws_client_maps_listmaps:
    path:     /maps/listmaps
    defaults: { _controller: WSClientBundle:Maps:listmaps }
ws_client_maps_listmapsdepart:
    path:     /maps/listmapsdepart
    defaults: { _controller: WSClientBundle:Maps:listmapsdepart }
ws_client_maps_listmapspardepart:
    path:     /maps/listmapspardepart
    defaults: { _controller: WSClientBundle:Maps:listmapspardepart }



ws_client_adminmultipdv_performancesadminpdv:
    path:     /adminmultipdv/performancesadminpdv
    defaults: { _controller: WSClientBundle:Adminmultipdv:performancesadminpdv }
ws_client_adminmultipdv_nombredereclamationagentpdvvente:
    path:     /adminmultipdv/nombredereclamationagentpdvvente
    defaults: { _controller: WSClientBundle:Adminmultipdv:nombredereclamationagentpdvvente }
ws_client_adminmultipdv_depositinitialconsommeparservice:
    path:     /adminmultipdv/depositinitialconsommeparservice
    defaults: { _controller: WSClientBundle:Adminmultipdv:depositinitialconsommeparservice }
ws_client_adminmultipdv_performanceagent:
    path:     /adminmultipdv/performanceagent
    defaults: { _controller: WSClientBundle:Adminmultipdv:performanceagent }
ws_client_adminmultipdv_bilandeposit:
    path:     /adminmultipdv/bilandeposit
    defaults: { _controller: WSClientBundle:Adminmultipdv:bilandeposit }
ws_client_adminmultipdv_listmap:
    path:     /adminmultipdv/listmap
    defaults: { _controller: WSClientBundle:Adminmultipdv:listmap }
ws_client_adminmultipdv_historiquerecouvrement:
    path:     /adminmultipdv/historiquerecouvrement
    defaults: { _controller: WSClientBundle:Adminmultipdv:historiquerecouvrement }
ws_client_adminmultipdv_historiquereclamation:
    path:     /adminmultipdv/historiquereclamation
    defaults: { _controller: WSClientBundle:Adminmultipdv:historiquereclamation }
ws_client_adminmultipdv_activiteservices:
    path:     /adminmultipdv/activiteservices
    defaults: { _controller: WSClientBundle:Adminmultipdv:activiteservices }
ws_client_adminmultipdv_demanderetraitfond:
    path:     /adminmultipdv/demanderetraitfond
    defaults: { _controller: WSClientBundle:Adminmultipdv:demanderetraitfond }
ws_client_adminmultipdv_listmajcautions:
    path:     /adminmultipdv/listmajcautions
    defaults: { _controller: WSClientBundle:Adminmultipdv:listmajcautions }
ws_client_adminmultipdv_modifymajcaution:
    path:     /adminmultipdv/modifymajcaution
    defaults: { _controller: WSClientBundle:Adminmultipdv:modifymajcaution }



ws_client_comptapdv_totaloperationparapi:
    path:     /comptapdv/totaloperationparapi
    defaults: { _controller: WSClientBundle:Comptapdv:totaloperationparapi }
ws_client_comptapdv_totalenvoiesparapi:
    path:     /comptapdv/totalenvoiesparapi
    defaults: { _controller: WSClientBundle:Comptapdv:totalenvoiesparapi }
ws_client_comptapdv_totalreceptionsparapi:
    path:     /comptapdv/totalreceptionsparapi
    defaults: { _controller: WSClientBundle:Comptapdv:totalreceptionsparapi }
ws_client_comptapdv_totalfraistransfertpercueparapi:
    path:     /comptapdv/totalfraistransfertpercueparapi
    defaults: { _controller: WSClientBundle:Comptapdv:totalfraistransfertpercueparapi }
ws_client_comptapdv_totalcommissionparapi:
    path:     /comptapdv/totalcommissionparapi
    defaults: { _controller: WSClientBundle:Comptapdv:totalcommissionparapi }
ws_client_comptapdv_totaloperationall:
    path:     /comptapdv/totaloperationall
    defaults: { _controller: WSClientBundle:Comptapdv:totaloperationall }
ws_client_comptapdv_totalenvoiesall:
    path:     /comptapdv/totalenvoiesall
    defaults: { _controller: WSClientBundle:Comptapdv:totalenvoiesall }
ws_client_comptapdv_totalreceptionsall:
    path:     /comptapdv/totalreceptionsall
    defaults: { _controller: WSClientBundle:Comptapdv:totalreceptionsall }
ws_client_comptapdv_totalfraistransfertpercuesall:
    path:     /comptapdv/totalfraistransfertpercuesall
    defaults: { _controller: WSClientBundle:Comptapdv:totalfraistransfertpercuesall }
ws_client_comptapdv_totalcommissionall:
    path:     /comptapdv/totalcommissionall
    defaults: { _controller: WSClientBundle:Comptapdv:totalcommissionall }
ws_client_comptapdv_ajoutservice:
    path:     /comptapdv/ajoutservice
    defaults: { _controller: WSClientBundle:Comptapdv:ajoutservice }
ws_client_comptapdv_ajoutcharge:
    path:     /comptapdv/ajoutcharge
    defaults: { _controller: WSClientBundle:Comptapdv:ajoutcharge }
ws_client_comptapdv_listecharge:
    path:     /comptapdv/listecharge
    defaults: { _controller: WSClientBundle:Comptapdv:listecharge }
ws_client_comptapdv_supprimerservice:
    path:     /comptapdv/supprimerservice
    defaults: { _controller: WSClientBundle:Comptapdv:supprimerservice }
ws_client_comptapdv_modifierservice:
    path:     /comptapdv/modifierservice
    defaults: { _controller: WSClientBundle:Comptapdv:modifierservice }
ws_client_comptapdv_approvisionner:
    path:     /comptapdv/approvisionner
    defaults: { _controller: WSClientBundle:Comptapdv:approvisionner }
ws_client_comptapdv_listecaisse:
    path:     /comptapdv/listecaisse
    defaults: { _controller: WSClientBundle:Comptapdv:listecaisse }
ws_client_comptapdv_listeservice:
    path:     /comptapdv/listeservice
    defaults: { _controller: WSClientBundle:Comptapdv:listeservice }
ws_client_comptapdv_listerevenu:
    path:     /comptapdv/listerevenu
    defaults: { _controller: WSClientBundle:Comptapdv:listerevenu }

ws_client_crm_portefeuille:
    path:     /crm/portefeuille
    defaults: { _controller: WSClientBundle:Crm:portefeuille }

ws_client_crm_relance:
    path:     /crm/relance
    defaults: { _controller: WSClientBundle:Crm:relance }

ws_client_crm_promotion:
    path:     /crm/promotion
    defaults: { _controller: WSClientBundle:Crm:promotion }

ws_client_crm_prospection:
    path:     /crm/prospection
    defaults: { _controller: WSClientBundle:Crm:prospection }

ws_client_crm_suivicommande:
    path:     /crm/suivicommande
    defaults: { _controller: WSClientBundle:Crm:suivicommande }

ws_client_crm_servicepoint:
    path:     /crm/servicepoint
    defaults: { _controller: WSClientBundle:Crm:servicepoint }
    
ws_client_comptapdv_listevente:
    path:     /comptapdv/listevente
    defaults: { _controller: WSClientBundle:Comptapdv:listevente }

ws_client_comptapdv_gestionreporting:
    path:     /gestionreporting/gestionreporting
    defaults: { _controller: WSClientBundle:Gestionreporting:gestionreporting }


ws_client_comptapdv_servicepoint:
    path:     /gestionreporting/servicepoint
    defaults: { _controller: WSClientBundle:Gestionreporting:servicepoint }


ws_client_comptapdv_ajoutdepense:
    path:     /gestionreporting/ajoutdepense
    defaults: { _controller: WSClientBundle:Gestionreporting:ajoutdepense }


ws_client_comptapdv_reclamation:
    path:     /gestionreporting/reclamation
    defaults: { _controller: WSClientBundle:Gestionreporting:reclamation }


ws_client_comptapdv_demandepret:
    path:     /demandepret/demandepret
    defaults: { _controller: WSClientBundle:Demandepret:demandepret }


ws_client_comptapdv_ajoutdemandepret:
    path:     /demandepret/ajoutdemandepret
    defaults: { _controller: WSClientBundle:Demandepret:ajoutdemandepret }

ws_client_comptapdv_consulterpret:
    path:     /consulterpret/consulterpret
    defaults: { _controller: WSClientBundle:Consulterpret:consulterpret }

