services:
#    ws_client.example:
#        class: WSClientBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ws_api_client_tnt:
        class: WSClientBundle\Services\TntService
        # arguments:
          # - "@doctrine.orm.default_entity_manager"
          # - "@test_server_authentification"
    ws_api_client_postcash:
        class: WSClientBundle\Services\PostCashService
